[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/leakguard",
    "crates/bridges",
    "crates/socks",
    "crates/telemetry",
    "crates/transparent",
    "crates/tui",
    "crates/cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["kernel-x"]
license = "MIT"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs", "io-util", "sync", "net", "signal", "time", "process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
