[package]
name = "anonet-bridges"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

anonet-core = { path = "../core" }
arti-client = { version = "0.46", features = ["tokio", "rustls", "bridge-client", "pt-client"] }
tempfile = "3"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
