[package]
name = "anonet-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

arti-client = { version = "0.46", features = ["tokio", "rustls", "bridge-client", "pt-client", "onion-service-client"] }
tor-rtcompat = { version = "0.46", features = ["tokio", "rustls"] }
tor-config = "0.46"

[dev-dependencies]
tempfile = "3"
