[package]
name = "anonet-socks"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
anonet-core = { path = "../core" }
arti-client = { version = "0.46", features = ["tokio", "rustls"] }
